name: Generate Website

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Website
        env:
          NUXT_APP_BASE_URL: /wahlen/
        run: pnpm generate

      - name: Upload generated Website
        uses: actions/upload-artifact@v4
        with:
          name: www.stupa.th-koeln.de
          path: .output/public
